name = "b2-worker"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[[rules]]
type = "Text"
fallthrough = true
globs = [
  "**/*.css",
  "**/*.rule",
  "**/*.raw.js"
]

[[kv_namespaces]]
binding = "KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
